name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set List Values
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          listValues: 'value1,value2,value3'  # This is where you define the input

      - name: Show List Values
        run: echo "List Values: $LIST_VALUES"
