name: Organization CI

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
  inputs:
    listValues:
      description: 'A list of values to process'
      required: true
      default: 'value1,value2,value3'

    steps:
      - uses: actions/checkout@v4
        with:
        path: ./package.json

      - name: Run a one-line script
        run: echo Hello from Organization
